--Determine the percentage of total revenue generated by each product category and identify the category that generates the highest percentage of revenue. 
SELECT 
	PC.Name,
	CAST(SUM(SOD.UnitPrice) AS DECIMAL (18,2)) AS TotalRevenuePerCategory,
	CAST(SUM(SUM(SOD.UnitPrice)) OVER()  AS DECIMAL (18,2)) AS TotalRevenue,
	SUM(SOD.UnitPrice) / SUM(SUM(SOD.UnitPrice)) OVER () * 100 AS TotalPerctentage
FROM
	Sales.SalesOrderDetail AS SOD
LEFT JOIN
	Production.Product AS P
ON SOD.ProductID = P.ProductID
LEFT JOIN 
	Production.ProductSubCategory AS PSC
ON P.ProductSubcategoryID = PSC.ProductSubcategoryID
LEFT JOIN
	Production.ProductCategory AS PC
ON PC.ProductCategoryID = PSC.ProductCategoryID
GROUP BY
	PC.Name
ORDER BY 
	TotalRevenuePerCategory DESC
